server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1
      path-mapping:
        health: health

springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui.html
  api-docs:
    path: /api/v1/openapi.json
